### PR TITLE
Update to 0.89

### PR DESCRIPTION
**Pull request by anmol26s**

### CODE REVIEW

**Comment by anmol26s** [comment]
Need testing. I don't use this app. Someone emailed me and pointed out that the current source is corrupt. So  just updating the sources in a hope that the app will still work with the updated sources.

**Comment by alexAubin** [comment]
Okay, thanks for the PR (I doubled checked the sha256sum and it's good)

We'd need someone to at least check the upgrade

(Also we should consider flagging this app as 'working' in the community list :s )

**Comment by authago** [comment]
Tried to install, but it looks like https://releases.wekan.team is offline.

**Comment by authago** [comment]
It's online again

**Comment by authago** [comment]
Can't check an upgrade, installed on a fresh yunohost.
App is running fine. Will report back in case of issues.
Thx!
```
Choose a domain name for Wekan (default: ####.###):
Choose a path for Wekan (default: /wekan):
Is it a public application? [0 | 1] (default: 0): 1
######################################################################## 100,0%
Waarschuwing: --2018-04-20 17:46:44--  https://www.mongodb.org/static/pgp/server-3.2.asc
Waarschuwing: Herleiden van www.mongodb.org (www.mongodb.org)... 52.206.222.245
Waarschuwing: Verbinding maken met www.mongodb.org (www.mongodb.org)|52.206.222.245|:443... verbonden.
Waarschuwing: HTTP-verzoek is verzonden; wachten op antwoord... 200 OK
Waarschuwing: Lengte: 1674 (1,6K) [text/plain]
Waarschuwing: Wordt opgeslagen als: ‘STDOUT’
Waarschuwing:
Waarschuwing:      0K .                                                     100% 17,9M=0s
Waarschuwing:
Waarschuwing: 2018-04-20 17:46:44 (17,9 MB/s) - geschreven naar standaarduitvoer [1674/1674]
Waarschuwing:
Waarschuwing: 2018-04-20 17:47:51 URL:https://releases.wekan.team/wekan-0.85.tar.gz [75720556/75720556] -> "wekan-0.85.tar.gz" [1]
Waarschuwing: npm WARN lifecycle meteor-dev-bundle@0.0.0~install: cannot run in wd %s %s (wd=%s) meteor-dev-bundle@0.0.0 node npm-rebuild.js /var/www/wekan/programs/server
Waarschuwing: npm WARN meteor-dev-bundle@0.0.0 No description
Waarschuwing: npm WARN meteor-dev-bundle@0.0.0 No repository field.
Waarschuwing: npm WARN meteor-dev-bundle@0.0.0 No license field.
Waarschuwing:
Waarschuwing: Created symlink from /etc/systemd/system/multi-user.target.wants/mongod.service to /lib/systemd/system/mongod.service.
Waarschuwing: Created symlink from /etc/systemd/system/multi-user.target.wants/wekan.service to /etc/systemd/system/wekan.service.
Succes! The SSOwat configuration has been generated
Succes! Installatie voltooid

```

**Comment by alexAubin** [comment]
Okay, thanks for the feedback !

**Comment by authago** [comment]
So far so good!
Could test an upgrade if I was able to install 77 by placing it local I think.
However this file:
https://github.com/wekan/wekan/archive/v0.77.tar.gz 
shows me a different sha256sum: 99EC106170A8487FCB7E8813479A4A10147DB206A1A47DC118202EC3AB25BF6C
which prevents install?

**Comment by alexAubin** [comment]
>Could test an upgrade if I was able to install 77 by placing it local I think.
However this file:
https://github.com/wekan/wekan/archive/v0.77.tar.gz
shows me a different sha256sum: 99EC106170A8487FCB7E8813479A4A10147DB206A1A47DC118202EC3AB25BF6C
which prevents install?

That seemed like a nice approach, until i realized that this apparently isn't the archive we're looking for since it looks like "just sources" but we need the pre-built version I think (which is way bigger) :confused: 

Anyway, I did tried some upgrade from version 0.80 which was the oldest available (sigh) and it sounds fine. In the process, I realized they were up to 0.89 by now (it's like they do one release every two or three days :|) so I updated the app.src. Also tweaked the manifest.json version (otherwise the actual upgrade is not done in yunohost)

Soooo Yolomerging ! Thanks everybody !

**Pull request merged**
