### PR TITLE
Properly remove service integration in Buster

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- Service integration remains even after the app (or MongoDB actually) is removed.

## Solution
- Use the right service name in service removal.

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by Tagadda** [comment]
I had this package installed before. I can't install main neither testing
https://paste.yunohost.org/raw/uhojafiyuk

**Comment by yalh76** [comment]
> 
> 
> I had this package installed before. I can't install main neither testing
> https://paste.yunohost.org/raw/uhojafiyuk

would be better to open a specific issue ;)

**Pull request merged**
